//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinh
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIEM
    {
        public string MaDiem { get; set; }
        public string MaMonHoc { get; set; }
        public string MaHocSinh { get; set; }
        public string NamHoc { get; set; }
        public string HocKy { get; set; }
        public Nullable<double> DiemTX { get; set; }
        public Nullable<double> DiemGK { get; set; }
        public Nullable<double> DiemCK { get; set; }
        public Nullable<double> DiemTB { get; set; }
        public string MaXepLoai { get; set; }
    
        public virtual HOCSINH HOCSINH { get; set; }
        public virtual MONHOC MONHOC { get; set; }
        public virtual XEPLOAI XEPLOAI { get; set; }
    }
}
